### PR TITLE
Improved option lists

### PR DESCRIPTION
**Pull request by lukasewvd**
- **NOTE:** Ensure that you also have the updated code from the d2-tracker: https://github.com/dhis2/d2-tracker/pull/4.

- https://jira.dhis2.org/browse/DHIS2-2063

- When not all options are displayed in a list (because of maxOptionLimit) a label is added to the bottom of the list with information telling the user that there are X more options that they can try using the search bar for.

option-list-improvment

### CODE REVIEW

**Comment by lukasewvd** [comment]
For fixing merge conflict, replace the conflict with this:

> move_permanently = Move permanently
> onetime_referral = One-time referral
> are_you_sure_you_want_to_move_permanently = Are you sure you want to move patient permanently?
> more_options_available=more options available, try searching...
> ok=OK
> can_not_add_new_enrollment=Can not add a new enrollment because this program only allows one enrollment.

**Comment by abyot** [comment]
Looks great. but can we think of more of an across the board solution - may be a directive or something like that?

We have options everywhere - registration, searching, data entry both custom and default forms of tracker and event capture apps.

**Comment by lukasewvd** [comment]
Yes, that would be more desirable. I will look into it. This is more of an example of how it can be done.

**Comment by lukasewvd** [comment]
The directive is now finished. If you want to test it, please ensure that you also have this code from the d2-tracker: https://github.com/dhis2/d2-tracker/pull/4.

**Pull request merged**
