### PR TITLE
chore: allow core app override

### PR DESCRIPTION
**Pull request by varl**

### CODE REVIEW

**Review by amcgee — APPROVED** [review]
Thanks @varl !

Cc @Bekkalizer @Philip-Larsen-Donnelly

**Comment by Bekkalizer** [comment]
Thanks. This was actually already done and tested here: https://github.com/dhis2/tracker-capture-app/commit/f49c2f1260f7c759a00c2abd748b8d42ad812569
We also need to copy the manifest.webapp to the build dir, as done in the linked commit.

**Review by Bekkalizer — APPROVED** [review]

**Comment by varl** [comment]
@Bekkalizer it wasn't ported to `master`, was that intentional ?

**Comment by Bekkalizer** [comment]
No, it was intended to go into master as well - but was done outside normal processes(there was no jira), and therefore fell between chairs.

**Pull request merged**
